### ISSUE TITLE
Gestion des users

### ISSUE THREAD

**Issue by storm1er** [Shikatamo/OGE#17]
## Quoi :  
Gestion des users, la plus simple possible pour la commodité et les futurs évolutions :   
- Pas de mot de passe, connexion via des liens que l'on envoi par mail. (1)
- On fera une gestion des droits plus tard, donc pas de rôle assigné ni d'autorisation. (2)
- Champs simple qui correspondent à un potentiel annuaire : 
- - Nom, Prénom, Téléphone, Mail - Tous obligatoire

Prévu pour la milestone 1.5

(1) : L'absence de mot de passe permet d'éviter la gestion "mot de passe oublié"
(1) : Permet de s'assurer que le mail juste, car validation obligatoire avant toute création d'user.
(1) : Avec le temps les adhérents seront des user, pour éviter les problèmes d'encryption de mot de passe, passé par un système de token à usage unique semble moins risqué.
(1) : *"Oui mais si on craque ma boîte mail"* : Je pense que le type qui prend soit de choper ta boite mail va plutôt regarder comment accéder à ton compte en banque ...

(2) : Une gestion des droits *(et non de rôles)* dans un élément externe.
(2) : Permettra de mettre en place la première version du site plus rapidement
(2) : Va faciliter la possibilité de faire du versioning / log de toutes les activités pour éviter les conflits humains qui pourrait arriver à cause de tel ou tel élément modifié par X ou Y à tel moment.

### Faisabilité / Spec complète : 
- [ ] OK - _Description complète et faisable_
- [X] NOK - _Description incomplète, besoin de renseignement supplémentaire ou faisabilité incertaine_
- [ ] KO - _Infaisable en l'état, besoin de spec particulière_

### Description / Spec : 
_Détail sur le *comment* se sera fait et avec quels outils / framework / plugin / ... selon la base du projet_

- [ ] La page du wiki existent pour cette issue : #[Issue `Wiki/Page`]
- [X] Il faut compléter la wiki pour cette issue : #[Issue `Wiki/Page`]
- [ ] Ceci est un `Web/Enhancement` : #[Issue `Web/Feature` qui correspond]
 
#### Milestone v1.0 : 
- En tant que membre je peux me connecter
- En tant que membre je peux décrire les pratiques #14  
- En tant que membre je peux créer des flash info #11   
- En tant que membre je peux créer des événements #10 
- En tant que membre je peux modifier le(s) lieu(x) #9 
- En tant que membre je peux modifier mon CV #8 
- En tant que membre je peux modifier les tarifs #2 
- En tant que membre je peux mettre à jour les horaires #1 
#### Milestone v1.5 : 
- En tant que membre ayant droit (1) je peux modifier les droits des autres
- En tant que membre ayant droit (1) je ne peux pas retirer mon propre droit d'édition de droit (2)
- Toutes les User-Story de la v1.0 mais à conditions d'ayant droit correspondant
#### Milestone v2.0 : 
- En tant que membre je peux créer des adhérents ?

(1) : Droit d'édition de droit
(2) : Pour éviter qu'un jour quelqu'un ai la merveilleuse idée de supprimer son propre droit puis de s'en plaindre ...

**Comment by storm1er** [comment]
@Shikatamo tu confirmes ?

**Comment by Shikatamo** [comment]
Ça me semble logique comme ordre de priorités. 

Je comprends pas trop ce que tu veux dire par une connexion par lien mail. Tu parles des "super users" (le bureau) ou de tous les utilisateurs ? 
Parce que du coup on évite le problème du "j'ai perdu mon mdp" mais pas le problème du "je trouve plus la bonne url".
Et si tu parle d'une connexion avec un style 2oauth avec validation par mail à chaque tentative de connections ça risque d'être laborieux pour des personnes qui ont du mal avec des outils numériques.

**Comment by storm1er** [comment]
> Ça me semble logique comme ordre de priorités. 
> 
> Je comprends pas trop ce que tu veux dire par une connexion par lien mail. Tu parles des "super users" (le bureau) ou de tous les utilisateurs ?

Tout les utilisateurs
> Parce que du coup on évite le problème du "j'ai perdu mon mdp" mais pas le problème du "je trouve plus la bonne url".

Ton cas est impossible, je me suis mal exprimé : 
Je pensais à ça : 
- Tu vas sur le mon-asso.com
- **"Se connecter"**
- Tu renseigne ton mail
- **"Un mail avec un lien vers l'administration vous a été envoyé"**
- Tu vas dans tes mails *(ça tout le monde connais => 99% de notre cible en tout cas)*
- Tu ouvres le mail reçu
- Tu cliques sur le gros bouton "Gérer mon site" *(qui est en fait un lien avec un token à usage unique, valide quelques heures uniquement)*
- **"Bienvenue sur la page d'accueil de l'administration"**

> Et si tu parle d'une connexion avec un style 2oauth avec validation par mail à chaque tentative de connexion ça risque d'être laborieux pour des personnes qui ont du mal avec des outils numériques.

Pas une validation, directement un lien de connexion comme expliqué ci dessus.

**Comment by Shikatamo** [comment]
ça reste une complication perso j'ai l'impression. Ça les obliges à utiliser une application tierce à chaque fois qu'ils veulent faire une modif sur le site. 

A noter mais faudra penser à leur proposer des solutions alternatives.

**Comment by storm1er** [comment]
Je tiens tout particulièrement à éviter le mot de passe : 
Si on leurs propose ça va finir par
- "On fera avec",
- "On le **notera** dans un coin, un **postit**, ..."

Puis quelques jours après la v1.0 on va avoir le shit-storm habituelle (&copy;)
- "Je trouve pas mon mot de passe"
- "J'arrive pas à utiliser *mot de passe oublié*" 
- "Tu peux me donner mon mot de passe ?"

Je te suis, mais si j'ai raison, c'est toi qui fera le suivi des mots de passe, j'ai déjà donné pour ça xD

*La sécurité ça fait parti des choses qu'il ne faut pas laisser au client, sauf quand il s'y connais.*

**Comment by storm1er** [comment]
J'avais complètement oublié que Firebase gérait tout seul les méthodes d'authentifications ...

https://firebase.google.com/docs/auth/#how_does_it_work

**Comment by storm1er** [comment]
CR note rapide

- Prévoir les adhérent sur le long terme

**Comment by storm1er** [comment]
CR note rapide : 

- pas de gestion des droits détaillé par pages, etc ... : juste des rôles simplifié
- administration plus générale (j'imaginais des affichage spécifique à chaque user)
